### ISSUE TITLE
mapmap not receiving OSC messages

### ISSUE THREAD

**Issue by philippevandal** [mapmapteam/mapmap#433] opened 2018-05-21 16:43 UTC
hellohello,

tried the processing/mapmap sketch from the https://github.com/mapmapteam/processing-mapmap github though nothing seems to be received on the mapmap side. I printed the OSC message on the processing side with the oscP5 .print() and voilà:

-OscMessage----------
received from	null:0
addrpattern	/mapmap/paint/uri
typetag	is
[0] 1
[1] /tmp/to_mapmap_1.jpg

---------------------

Nothing is displayed in the console log of mapmap. What could be the issue? Tried other ports, no success. 

Important detail: I changed the version in the .mmp file to <project version="0.6.1"> so it could be opened.

**Comment by philippevandal** [comment] 2018-05-23 12:26
MacOS High Sierra, I did press s ! Though nothing

**Comment by philippevandal** [comment] 2018-05-24 19:52
Re-installed the oscP5 library, nothing is received my mapmap.

**Comment by aalex** [comment] 2018-05-24 20:22
Should this ticket really be closed?

**Comment by aalex** [comment] 2018-05-24 20:26
MapMap doesn't receive OSC on macOS. See #352

**Comment by aalex** [comment] 2018-05-24 20:27
This is a duplicate of #283

**Closed by aalex** 2018-05-24 20:27 UTC
Labels: OSC, bug, question

**Comment by aalex** [comment] 2018-05-24 20:29
(I am sorry that I did not realize this earlier. To make bugs easier to track, please use only the GItHub issues system, and include a complete technical sheet in your initial bug description)
