### ISSUE TITLE
Ubuntu 18.04: built from master, segfault - QObject::startTimer: Timers can only be used with threads started with QThread

### ISSUE THREAD

**Issue by revast** [mapmapteam/mapmap#443] opened 2018-08-31 20:40 UTC
./mapmap 
QObject::startTimer: Timers can only be used with threads started with QThread
QObject::startTimer: Timers can only be used with threads started with QThread
QObject::startTimer: Timers can only be used with threads started with QThread
QObject::startTimer: Timers can only be used with threads started with QThread
QObject::startTimer: Timers can only be used with threads started with QThread
QObject::startTimer: Timers can only be used with threads started with QThread
QObject::startTimer: Timers can only be used with threads started with QThread
QObject::startTimer: Timers can only be used with threads started with QThread
QObject::startTimer: Timers can only be used with threads started with QThread
QObject::startTimer: Timers can only be used with threads started with QThread
QObject::startTimer: Timers can only be used with threads started with QThread
QObject::startTimer: Timers can only be used with threads started with QThread
QObject::startTimer: Timers can only be used with threads started with QThread
QObject::startTimer: Timers can only be used with threads started with QThread
QObject::startTimer: Timers can only be used with threads started with QThread
QObject::startTimer: Timers can only be used with threads started with QThread
QObject::startTimer: Timers can only be used with threads started with QThread
QObject::startTimer: Timers can only be used with threads started with QThread
QObject::startTimer: Timers can only be used with threads started with QThread
Segmentation fault

I also tried 0.5.0 from xenial, it crashes with the same message

**Comment by aalex** [comment] 2018-08-31 22:04
Thank you for your report!

How can we reproduce this issue?

**Comment by aalex** [comment] 2018-08-31 22:05
It happens on Ubuntu 18.04 and on 16.04.

**Comment by revast** [comment] 2018-09-01 07:55
> How can we reproduce this issue?

I suggest you get a ready-to run vm from https://www.osboxes.org/ubuntu/
Then I just did as advertised.. 

- install dependencies
- git clone mapmap master,
- the I tried the script and also qmake directly, 
- then make

when I run with ./mapmap, I get the error message

**Comment by 8mh8** [comment] 2018-12-03 17:35
Hey, I'm having the same issue after building 0.6.2.
Using Linux Mint 19 on an i7-8550U CPU.
`$uname -rm`
`4.15.0-39-generic x86_64`

Maybe I'm building the wrong one ? It happens with master as well. Or maybe this issue hasn't been addressed yet ? Anything I can do to provide more info ?

**Comment by aalex** [comment] 2018-12-03 17:36
Can you try the develop branch?

**Comment by 8mh8** [comment] 2018-12-03 17:56
I just did. Same old same old. "segfault".
`Project MESSAGE: MapMap version: 0.6.3`
I'm building using provided script. Anything else I can try ?

**Comment by aalex** [comment] 2018-12-05 01:16
Still the same error about the Timer? 
(another known segfault is when there is no graphical user interface)

**Comment by 8mh8** [comment] 2018-12-05 10:52
Yes, the segfault concerns the timer, not the GUI. That being said, this happens at launch and crashes the program so I never do get a GUI anyway.
The error message is strictly the same as the one that opened this thread except for the last line which contains the additional : 

`Segmentation fault (core dumped)`

**Comment by skankerror** [comment] 2020-01-08 18:35
Maybe same issue as #341 ?

**Comment by lilyCalla** [comment] 2020-01-30 01:04
This appears to be the same issue as #341. I tested on Linux Mint 19 before and after removing qt5ct. Removing qt5ct fixed it.

**Comment by sofian** [comment] 2020-04-01 19:06
This seems to be a duplicate of #341. Closing this one for now.

**Closed as completed by sofian** 2020-04-01 19:06 UTC
Labels: bug, platform_linux, points: 0
