### ISSUE TITLE
MapMap crashes

### ISSUE THREAD

**Issue by Glad2b4given** [mapmapteam/mapmap#470] opened 2019-12-31 17:31 UTC
I am new to mapmap. I have loaded a media source from a youtube free source file. It is in the mp4 format. When I select the rectangle + mask the app crashes and closes.

**Comment by sofian** [comment] 2019-12-31 17:38
Hi, thanks for your issue. Could you send us a link to the MP4 file so that we can try to reproduce the bug on our side?

**Comment by Glad2b4given** [comment] 2020-01-01 19:20
Thank you for your response. Here is a link to the media file I have imported to mapmap that results in a crash.  I copy this link to a youtube downloader and file converter at http://www.y2mate.com.  I then import the mp4 file. I have tried several medial files all with the same result.Thank you for any assistance you can provide. 
Greg Little
Free Christmas Tree Background Animation - No Copyright - HD Motion Graphics


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Free Christmas Tree Background Animation - No Copyright - HD Motion Gra...

100% FREE STOCK FOOTAGE - Free commercial use! No Copyright! No Credits Required! Royalty Free! https://bit.ly/2...
 |

 |

 |



    On Tuesday, December 31, 2019, 11:38:22 AM CST, Sofian Audry <notifications@github.com> wrote:  
 
 
Hi, thanks for your issue. Could you send us a link to the MP4 file so that we can try to reproduce the bug on our side?

**Comment by sofian** [comment] 2020-01-01 19:32
Sorry but I cannot see the link.

**Comment by Glad2b4given** [comment] 2020-01-01 19:58
Sorry, here is the link:
https://youtu.be/QbGAmkHkg64?list=PLcKa-34z76PtUr-n12AL9vhBNhttps://youtu.be/QbGAmkHkg64?list=PLcKa-34z76PtUr-n12AL9vhBNj4NwqtCKj4NwqtCK
Thank you.

**Comment by Glad2b4given** [comment] 2020-01-01 22:29
As an update I am able to load and open still pictures, however, video crashes the app
Thank you
Greg Little
    On Wednesday, January 1, 2020, 01:57:59 PM CST, Greg Little <gregp.little@yahoo.com> wrote:  
 
 Sorry, here is the link:
https://youtu.be/QbGAmkHkg64?list=PLcKa-34z76PtUr-n12AL9vhBNhttps://youtu.be/QbGAmkHkg64?list=PLcKa-34z76PtUr-n12AL9vhBNj4NwqtCKj4NwqtCK
Thank you.

**Comment by sofian** [comment] 2020-01-02 21:05
The link you sent me is a youtube video. Are you trying to run a video from a stream (URL)? Or are you downloading the video and trying to import it?

**Comment by sofian** [comment] 2020-01-02 22:05
Also, have a look at our recommended video formats:
https://github.com/mapmapteam/mapmap/wiki/Video-file-formats

Re-encoding files in Motion-JPEG or MPEG4 sometimes does the trick.

**Comment by sofian** [comment] 2020-04-01 15:49
Closing this for now since lacking information to reproduce bug.

**Closed as completed by sofian** 2020-04-01 15:49 UTC
Labels: bug, crash

**Comment by nickardiamond** [comment] 2021-02-23 13:37
I am having the same issue. I can import a mp4 but as soon as I select the mask, the program crashes. Doesn't matter what mp4 I import. I am on Windows 10.
