### ISSUE TITLE
Cannot compile on archlinux... Issue with QtAbstractPropertyBrowserPrivate

### ISSUE THREAD

**Issue by pietrondo** [mapmapteam/mapmap#367] opened 2017-11-28 11:00 UTC
Hello, I'm trying to compile the develop branch on my arch linux, but I have some erros..
thx

uname -a
Linux 4.13.12-1-zen

gcc -v
`Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --disable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp
Thread model: posix
gcc version 7.2.0 (GCC) 
`
now the errors

`src/app/mocs/moc_qtpropertybrowser.cpp: In static member function ‘static void QtAbstractPropertyBrowser::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)’:
src/app/mocs/moc_qtpropertybrowser.cpp:369:29: error: invalid use of incomplete type ‘class QtAbstractPropertyBrowserPrivate’
         case 4: _t->d_func()->slotPropertyInserted((*reinterpret_cast< QtProperty*(*)>(_a[1])),(*reinterpret_cast< QtProperty*(*)>(_a[2])),(*reinterpret_cast< QtProperty*(*)>(_a[3]))); break;
                             ^~
In file included from src/app/mocs/moc_qtpropertybrowser.cpp:9:0:
src/app/mocs/../../gui/contrib/qtpropertybrowser/src/qtpropertybrowser.h:263:18: note: forward declaration of ‘class QtAbstractPropertyBrowserPrivate’
     friend class QtAbstractPropertyBrowserPrivate;
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/mocs/moc_qtpropertybrowser.cpp:369:31: error: invalid use of incomplete type ‘class QtAbstractPropertyBrowserPrivate’
         case 4: _t->d_func()->slotPropertyInserted((*reinterpret_cast< QtProperty*(*)>(_a[1])),(*reinterpret_cast< QtProperty*(*)>(_a[2])),(*reinterpret_cast< QtProperty*(*)>(_a[3]))); break;
                               ^~~~~~~~~~~~~~~~~~~~
In file included from src/app/mocs/moc_qtpropertybrowser.cpp:9:0:
src/app/mocs/../../gui/contrib/qtpropertybrowser/src/qtpropertybrowser.h:263:18: note: forward declaration of ‘class QtAbstractPropertyBrowserPrivate’
     friend class QtAbstractPropertyBrowserPrivate;
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/mocs/moc_qtpropertybrowser.cpp:370:29: error: invalid use of incomplete type ‘class QtAbstractPropertyBrowserPrivate’
         case 5: _t->d_func()->slotPropertyRemoved((*reinterpret_cast< QtProperty*(*)>(_a[1])),(*reinterpret_cast< QtProperty*(*)>(_a[2]))); break;
                             ^~
In file included from src/app/mocs/moc_qtpropertybrowser.cpp:9:0:
src/app/mocs/../../gui/contrib/qtpropertybrowser/src/qtpropertybrowser.h:263:18: note: forward declaration of ‘class QtAbstractPropertyBrowserPrivate’
     friend class QtAbstractPropertyBrowserPrivate;
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/mocs/moc_qtpropertybrowser.cpp:370:31: error: invalid use of incomplete type ‘class QtAbstractPropertyBrowserPrivate’
         case 5: _t->d_func()->slotPropertyRemoved((*reinterpret_cast< QtProperty*(*)>(_a[1])),(*reinterpret_cast< QtProperty*(*)>(_a[2]))); break;
                               ^~~~~~~~~~~~~~~~~~~
In file included from src/app/mocs/moc_qtpropertybrowser.cpp:9:0:
src/app/mocs/../../gui/contrib/qtpropertybrowser/src/qtpropertybrowser.h:263:18: note: forward declaration of ‘class QtAbstractPropertyBrowserPrivate’
     friend class QtAbstractPropertyBrowserPrivate;
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/mocs/moc_qtpropertybrowser.cpp:371:29: error: invalid use of incomplete type ‘class QtAbstractPropertyBrowserPrivate’
         case 6: _t->d_func()->slotPropertyDestroyed((*reinterpret_cast< QtProperty*(*)>(_a[1]))); break;
                             ^~
In file included from src/app/mocs/moc_qtpropertybrowser.cpp:9:0:
src/app/mocs/../../gui/contrib/qtpropertybrowser/src/qtpropertybrowser.h:263:18: note: forward declaration of ‘class QtAbstractPropertyBrowserPrivate’
     friend class QtAbstractPropertyBrowserPrivate;
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/mocs/moc_qtpropertybrowser.cpp:371:31: error: invalid use of incomplete type ‘class QtAbstractPropertyBrowserPrivate’
         case 6: _t->d_func()->slotPropertyDestroyed((*reinterpret_cast< QtProperty*(*)>(_a[1]))); break;
                               ^~~~~~~~~~~~~~~~~~~~~
In file included from src/app/mocs/moc_qtpropertybrowser.cpp:9:0:
src/app/mocs/../../gui/contrib/qtpropertybrowser/src/qtpropertybrowser.h:263:18: note: forward declaration of ‘class QtAbstractPropertyBrowserPrivate’
     friend class QtAbstractPropertyBrowserPrivate;
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/mocs/moc_qtpropertybrowser.cpp:372:29: error: invalid use of incomplete type ‘class QtAbstractPropertyBrowserPrivate’
         case 7: _t->d_func()->slotPropertyDataChanged((*reinterpret_cast< QtProperty*(*)>(_a[1]))); break;
                             ^~
In file included from src/app/mocs/moc_qtpropertybrowser.cpp:9:0:
src/app/mocs/../../gui/contrib/qtpropertybrowser/src/qtpropertybrowser.h:263:18: note: forward declaration of ‘class QtAbstractPropertyBrowserPrivate’
     friend class QtAbstractPropertyBrowserPrivate;
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/mocs/moc_qtpropertybrowser.cpp:372:31: error: invalid use of incomplete type ‘class QtAbstractPropertyBrowserPrivate’
         case 7: _t->d_func()->slotPropertyDataChanged((*reinterpret_cast< QtProperty*(*)>(_a[1]))); break;
                               ^~~~~~~~~~~~~~~~~~~~~~~
In file included from src/app/mocs/moc_qtpropertybrowser.cpp:9:0:
src/app/mocs/../../gui/contrib/qtpropertybrowser/src/qtpropertybrowser.h:263:18: note: forward declaration of ‘class QtAbstractPropertyBrowserPrivate’
     friend class QtAbstractPropertyBrowserPrivate;
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:2685: src/app/objs/moc_qtpropertybrowser.o] Error 1
`

**Comment by aalex** [comment] 2018-03-13 13:59
Duplicate of ticket 368

**Comment by aalex** [comment] 2018-03-13 13:59
Did you try doing a fresh GIt clone?

**Comment by sofian** [comment] 2018-03-21 23:03
This is clearly related to #368 (and actually most likely the same bug).
See my comment here : https://github.com/mapmapteam/mapmap/issues/368#issuecomment-347995465

**Comment by sofian** [comment] 2018-03-22 13:37
I will classify this as a Duplicate of #368 and close it.

**Closed by sofian** 2018-03-22 13:37 UTC
Labels: bug, platform_linux

**Comment by sofian** [comment] 2018-03-25 15:40
Try a fresh clone: git clone -b develop git@github.com:mapmapteam/mapmap
