### ISSUE TITLE
The ppa is not signed and thus won't update 

### ISSUE THREAD

**Issue by dougdalton** [mapmapteam/mapmap#483] opened 2020-03-31 02:44 UTC
the ppa wont update because its not signed
so letting users know to  add [trusted] to the sources.d ppa would be helpful to users
and once doing apt-get update

you get an errror:
Ign:17 http://ppa.launchpad.net/mapmap/mapmap/ubuntu bionic/main amd64 c-n-f Metadata
Reading package lists... Done
E: Failed to fetch http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/bionic/main/binary-i386/Packages  404  Not Found [IP: 91.189.95.83 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by sofian** [comment] 2020-04-01 15:48
@aalex is this a duplicate of #456 ?

**Comment by dougdalton** [comment] 2020-04-01 16:29
I am using 18.04 LTS,  but I could migrate to another version

**Comment by aalex** [comment] 2020-04-01 18:42
We need to package MapMap for Bionic Beaver. See #426

**Closed as completed by aalex** 2020-04-01 18:42 UTC
Labels: duplicate
